# Site settings
title: cfSorry
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: "http://richardherbert.github.io" # the base hostname & protocol for your site
baseurl: "/cfsorry"

# Build settings
markdown: kramdown

exclude: ['CNAME','*.sublime-*']
